services:
  db:
    image: postgres:16
    volumes:
      - app_backend_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5436:5432"
  app:
    build:
      context: .
    environment:
      - PYTHONPATH=.
    volumes:
      - ./src:/app/src
    command: uv run src/main.py
    ports:
      - "8000:8000"

    depends_on:
      - db

volumes:
  app_backend_postgres: